// CLIENT

GET http://127.0.0.1:5000/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NDE2ODM2NSwianRpIjoiZjA4YjgwN2QtM2I4YS00YTk2LWI4YzYtZmE3NmJmOWQxNzdjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjg0MTY4MzY1LCJleHAiOjE2ODQxNzE5NjV9.wchOwa1jg6NJRHK09OtD--X1Ais5x8egu1SHNy_P7nI

###
GET http://127.0.0.1:5000/clients/all

###
GET http://127.0.0.1:5000/clients/contract_product/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NDE2ODM2NSwianRpIjoiZjA4YjgwN2QtM2I4YS00YTk2LWI4YzYtZmE3NmJmOWQxNzdjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjg0MTY4MzY1LCJleHAiOjE2ODQxNzE5NjV9.wchOwa1jg6NJRHK09OtD--X1Ais5x8egu1SHNy_P7nI

###
POST http://127.0.0.1:5000/clients/create
Content-Type: application/json

{
  "name": "Nathan",
  "email": "nathan@gmail.com",
  "password": "16678225"
}

###
POST http://127.0.0.1:5000/clients/login
Content-Type: application/json

{
  "email": "nathan@gmail.com",
  "password": "16678225"
}

//=====================================================================================

// PRODUCT

###
GET http://127.0.0.1:5000/products

###
POST http://127.0.0.1:5000/products/register
Content-Type: application/json

{
  "name": "P55",
  "value": 999,
  "type": "Avulso"
}

###
PUT http://127.0.0.1:5000/products/edit/1
Content-Type: application/json

{
  "name": "P88",
  "value": 1000
}

###
DELETE  http://127.0.0.1:5000/products/delete/9


