// CLIENT

GET http://127.0.0.1:5000/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NDIwNzc1OCwianRpIjoiZjdkNjAzNTEtNjc2ZS00ODBlLWE5NTYtZTViN2VhZmEzMWJmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNjg0MjA3NzU4LCJleHAiOjE2ODQyMTEzNTh9.IWcBTxOu2dLNUw4cWBFCV7bGpuDbFc9mutF9aeTQxQU

###
GET http://127.0.0.1:5000/clients/all

###
GET http://127.0.0.1:5000/clients/contract_product/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NDIwNzc1OCwianRpIjoiZjdkNjAzNTEtNjc2ZS00ODBlLWE5NTYtZTViN2VhZmEzMWJmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNjg0MjA3NzU4LCJleHAiOjE2ODQyMTEzNTh9.IWcBTxOu2dLNUw4cWBFCV7bGpuDbFc9mutF9aeTQxQU

###
POST http://127.0.0.1:5000/clients/create
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@gmail.com",
  "password": "16678225"
}

###
POST http://127.0.0.1:5000/clients/login
Content-Type: application/json

{
  "email": "gabriel@gmail.com",
  "password": "16678225"
}

//=====================================================================================

// PRODUCT

###
GET http://127.0.0.1:5000/products

###
POST http://127.0.0.1:5000/products/register
Content-Type: application/json

{
  "name": "P55",
  "value": 999,
  "type": "Avulso"
}

###
PUT http://127.0.0.1:5000/products/edit/1
Content-Type: application/json

{
  "name": "P88",
  "value": 200
}

###
DELETE  http://127.0.0.1:5000/products/delete/1


